lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600  # 1 heure d'expiration

    token_extractors:
        authorization_header:
            enabled: false  # Desactive l'extraction par header
        cookie:
            enabled: true   # Active l'extraction par http-only cookies 
            name: access_token
