security:    
    password_hashers:
        
        App\Entity\User: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User  # Entité utilisée pour l'authentification
                property: email      
       

    
    firewalls:
        
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Endpoint de connexion - génère un JWT
        login:
            pattern: ^/api/login$
            stateless: true              
            lazy: true           
            # json_login: gére par la méthode de AuthController personnalisée « login »                

        # Routes API protégées par JWT
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider  
            jwt: ~                   

    
    access_control:
        # Routes publiques

        # Authentification
        - { path: ^/api/login$,       roles: PUBLIC_ACCESS }
        - { path: ^/api/register$,    roles: PUBLIC_ACCESS }
        - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }  
        - { path: ^/api/products,     roles: PUBLIC_ACCESS }
        - { path: ^/api/verify-email, roles: PUBLIC_ACCESS }
        
        # categorie
        - { path: ^/api/category/all, roles: PUBLIC_ACCESS }
        - { path: ^/api/category/\d+$, roles: PUBLIC_ACCESS, methods: [GET] }

        # product
        - { path: ^/api/product/all, roles: PUBLIC_ACCESS }
        - { path: ^/api/product/search, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/product/\d+(/.*), roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/product/category/\d+(/.*)?, roles: PUBLIC_ACCESS, methods: [GET] }

        # Routes requis JWT
        - { path: ^/api,              roles: IS_AUTHENTICATED_FULLY }
        

when@test:
    security:
        password_hashers:
            
            App\Entity\User:
                algorithm: auto
                cost: 4          
                time_cost: 3     
                memory_cost: 10  
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
