# config/services.yaml
parameters:
    app.frontend_url: '%env(APP_FRONTEND_URL)%'
    app.email_sender: '%env(APP_EMAIL_SENDER)%'
    upload_dir: '%kernel.project_dir%/public/uploads'
    max_upload_size: '2M'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\Service\AttachmentService:
        arguments:
            $uploadDir: '%upload_dir%'
            $maxUploadSize: '%max_upload_size%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Explicit service configuration for AuthService
    App\Service\AuthService:
        arguments:
            $appFrontendUrl: '%app.frontend_url%'
            $mailer: '@mailer.mailer'